name: 'Terraform Configuration Validation'

on:
  pull_request:
    branches:
    - main
  
jobs:
  terraform-unit-tests:
    name: 'Terraform Unit Tests'
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      working-directory: ./apps/demo-time/definition
      run: terraform init

    # Validate terraform files
    - name: Terraform Validate
      working-directory: ./apps/demo-time/definition
      run: terraform validate

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      working-directory: ./apps/demo-time/definition
      run: terraform fmt -check -recursive -diff

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      id: tf-plan
      working-directory: ./apps/demo-time/definition
      run: |
        terraform plan
